export const GET_CATEGORY='GET_CATEGORY';
export const GET_CATEGORY_LOADING='GET_CATEGORY_LOADING';
export const GET_CATEGORY_SUCCESS='GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_ERROR='GET_CATEGORY_ERROR';



export const ADD_CATEGORY='ADD_CATEGORY';
export const ADD_CATEGORY_LOADING='ADD_CATEGORY_LOADING';
export const ADD_CATEGORY_SUCCESS='ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_ERROR='ADD_CATEGORY_ERROR';


export const EDIT_CATEGORY='EDIT_CATEGORY';
export const EDIT_CATEGORY_LOADING='EDIT_CATEGORY_LOADING';
export const EDIT_CATEGORY_SUCCESS='EDIT_CATEGORY_SUCCESS';
export const EDIT_CATEGORY_ERROR='EDIT_CATEGORY_ERROR';


export const DELETE_CATEGORY='DELETE_CATEGORY';
export const DELETE_CATEGORY_LOADING='DELETE_CATEGORY_LOADING';
export const DELETE_CATEGORY_SUCCESS='DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_ERROR='DELETE_CATEGORY_ERROR';

export const EDIT_RULES_CATEGORY='EDIT_RULES_CATEGORY';
export const EDIT_RULES_CATEGORY_LOADING='EDIT_RULES_CATEGORY_LOADING';
export const EDIT_RULES_CATEGORY_SUCCESS='EDIT_RULES_CATEGORY_SUCCESS';
export const EDIT_RULES_CATEGORY_ERROR='EDIT_RULES_CATEGORY_ERROR';

export const RESET='RESET';

export const GET_CATEGORY_DETAIL_SUCCESS='GET_CATEGORY_DETAIL_SUCCESS';
export const GET_CATEGORY_DETAIL_LOADING='GET_CATEGORY_DETAIL_LOADING';
export const GET_CATEGORY_DETAIL_ERROR='GET_CATEGORY_DETAIL_ERROR';


export const GET_HANDLE_CODE_SUCCESS='GET_HANDLE_CODE_SUCCESS';
export const GET_HANDLE_CODE_LOADING='GET_HANDLE_CODE_LOADING';



export const GET_INTRODUCER_USER='GET_INTRODUCER_USER';
export const GET_INTRODUCER_USER_LOADING='GET_INTRODUCER_USER_LOADING';
export const GET_INTRODUCER_USER_SUCCESS='GET_INTRODUCER_USER_SUCCESS';
export const GET_INTRODUCER_USER_ERROR='GET_INTRODUCER_USER_ERROR';

export const DELETE_INTRODUCER_USER_LOADING='DELETE_INTRODUCER_USER_LOADING';
export const DELETE_INTRODUCER_USER_SUCCESS='DELETE_INTRODUCER_USER_SUCCESS';
export const DELETE_INTRODUCER_USER_ERROR='DELETE_INTRODUCER_USER_ERROR';


export const ADD_INTRODUCER_USER_LOADING='ADD_INTRODUCER_USER_LOADING';
export const ADD_INTRODUCER_USER_SUCCESS='ADD_INTRODUCER_USER_SUCCESS';
export const ADD_INTRODUCER_USER_ERROR='ADD_INTRODUCER_USER_ERROR';

export const RESET_USER='RESET_USER'