export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_LOADING='LOGIN_LOADING';
export const LOGIN_ERROR='LOGIN_ERROR';


export const LOGOUT_SUCCESS='LOGOUT_SUCCESS';
export const LOGOUT_LOADING='LOGOUT_LOADING';
export const LOGOUT_ERROR='LOGOUT_ERROR';

export const GET_USER_ID_SUCCESS='GET_USER_ID_SUCCESS';
export const GET_USER_ID_LOADING='GET_USER_ID_LOADING';
export const GET_USER_ID_ERROR='GET_USER_ID_ERROR';