export const GET_USER_DIEM='GET_USER_DIEM';
export const GET_USER_DIEM_SUCCESS='GET_USER_DIEM_SUCCESS';
export const GET_USER_DIEM_ERROR='GET_USER_DIEM_ERROR';
export const GET_USER_DIEM_LOADING='GET_USER_DIEM_LOADING';


export const GET_USER_CATEGORY_SUCCESS='GET_USER_CATEGORY_SUCCESS';
export const GET_USER_CATEGORY_LOADING='GET_USER_CATEGORY_LOADING';
export const GET_USER_CATEGORY_ERROR='GET_USER_CATEGORY_ERROR';


export const RESET_USER_CATEGORY_SUCCESS='RESET_USER_CATEGORY_SUCCESS';
export const RESET_USER_CATEGORY_LOADING='RESET_USER_CATEGORY_LOADING';
export const RESET_USER_CATEGORY_ERROR='RESET_USER_CATEGORY_ERROR';


export const ADD_USER_CATEGORY_SUCCESS='ADD_USER_CATEGORY_SUCCESS';
export const ADD_USER_CATEGORY_LOADING='ADD_USER_CATEGORY_LOADING';
export const ADD_USER_CATEGORY_ERROR='ADD_USER_CATEGORY_ERROR';



export const RESET='RESET';