export const GET_QUESTION_CATEGORY='GET_QUESTION_CATEGORY';
export const GET_QUESTION_CATEGORY_SUCCESS='GET_QUESTION_CATEGORY_SUCCESS';
export const GET_QUESTION_CATEGORY_ERROR='GET_QUESTION_CATEGORY_ERROR';
export const GET_QUESTION_CATEGORY_LOADING='GET_QUESTION_CATEGORY_LOADING';


export const ADD_QUESTION_CATEGORY_SUCCESS='ADD_QUESTION_CATEGORY_SUCCESS';
export const ADD_QUESTION_CATEGORY_LOADING='ADD_QUESTION_CATEGORY_LOADING';
export const ADD_QUESTION_CATEGORY_ERROR='ADD_QUESTION_CATEGORY_ERROR';
// export const GET_QUESTION_CATEGORY='GET_QUESTION_CATEGORY';

export const DELETE_QUESTION_CATEGORY_SUCCESS='DELETE_QUESTION_CATEGORY_SUCCESS';
export const DELETE_QUESTION_CATEGORY_LOADING='DELETE_QUESTION_CATEGORY_LOADING';
export const DELETE_QUESTION_CATEGORY_ERROR='DELETE_QUESTION_CATEGORY_ERROR';
// export const GET_QUESTION_CATEGORY='GET_QUESTION_CATEGORY';

// export const GET_QUESTION_CATEGORY='GET_QUESTION_CATEGORY';
// export const GET_QUESTION_CATEGORY='GET_QUESTION_CATEGORY';
// export const GET_QUESTION_CATEGORY='GET_QUESTION_CATEGORY';
// export const GET_QUESTION_CATEGORY='GET_QUESTION_CATEGORY';



export const GET_QUESTION_DETAIL_SUCCESS='GET_QUESTION_SUCCESS';
export const GET_QUESTION_DETAIL_LOADING='GET_QUESTION_DETAIL_LOADING';
export const GET_QUESTION_DETAIL_ERROR='GET_QUESTION_DETAIL_ERROR';



// export const GET_QUESTION='GET_QUESTION';


export const RESET="RESET";